import type { Metadata } from "next";
import "./globals.css";
import { Sriracha } from "next/font/google";

const sriracha = Sriracha({
  subsets: ["latin"],
  display: "swap",
  weight: "400",
  variable: "--font-sriracha",
});

export const metadata: Metadata = {
  title: "Note Editor",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${sriracha.variable} antialiased flex justify-center `}>
        {children}
      </body>
    </html>
  );
}
